# -*- coding: utf-8 -*-
"""Taaghche_Sentiment_Analysis_edit3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TUd8TTsyKf9aYoCxjEV9L3Hq5ARo1GUY

# Sentiment Analysis with ParsBERT

## I'm Ali Amani and I'm a Data Scientist intern at "DeepLearningCenter.ir".

## BERT Overview

BERT stands for Bi-directional Encoder Representation from Transformers is designed to pre-train deep bidirectional representations from unlabeled texts by jointly conditioning on both left and right context in all layers. The pretrained BERT model can be fine-tuned with just one additional output layer (in many cases) to create state-of-the-art models. This model can use for a wide range of NLP tasks, such as question answering and language inference, and so on without substantial task-specific architecture modification.


Natural Language Processing (NLP) tasks include sentence-level tasks or token-level tasks:

- **Sentence-Level:** Tasks such as Natural Language Inference (NLI) aim to predict the relationships between sentences by holistically analyzing them.
- **Token-Level:** Tasks such as Named Entity Recognition (NER), Question Answering (QA), the model makes predictions on a word-by-word basis.

In the pre-trained language representation, there are two primary strategies for applying to down-stream NLP tasks:

- Feature-based: They use task-specific architectures that include pre-training representation as additional features like Word2vec, ELMo, ...
- Fine-tunning: Introduce minimal task-specific parameters, and are trained on the down-stream tasks by merely tuning the pre-training parameters like GPT.

Before going more further into code, let me introduce **ParsBERT**.

## ParsBERT

Is a monolingual language model based on Google's BERT architecture. This model is pre-trained on large Persian corpora with various writing styles from numerous subjects (e.g., scientific, novels, news, ...) with more than **3.9M** documents, **73M** sentences, and **1.3B** words. For more information about ParsBERT, please check out our article: [arXiv:2005.12515](https://arxiv.org/abs/2005.12515).

[ParsBERT Repository](https://github.com/hooshvare/parsbert)

So, now you have a little understanding of BERT in total, we need to know how to use ParsBERT in our project. In the following tutorial, I would like to implement a fine-tuned model on the Sentiment Analysis task for TensorFlow and PyTorch. Stay tuned!

To stop google colab from disconnecting due to no interaction, you can do the following steps:
1- Open the developer tools in Colab by pressing Ctrl + Shift + I (or F12).
2- Click on the "Console" tab.
3- Copy and paste the JavaScript code in the cell below into the console.
4- Press Enter to run the code.

/**
 * ConnectButton function
 *
 * Logs a message to the console and clicks the "Connect" button in the top toolbar.
 */
function ConnectButton() {
  console.log("Connect pushed");
  document.querySelector("#top-toolbar > colab-connect-button").shadowRoot.querySelector("#connect").click();
}

/**
 * setInterval
 *
 * Calls the ConnectButton function every 60 seconds (60000 milliseconds).
 */
setInterval(ConnectButton, 60000);

To stop the automatic reconnection, simply clear the interval by running the following code in the console:
clearInterval(ConnectButton);
"""

def get_gpu_info():
  """
  Retrieves and displays information about the connected GPU.
  """

  # Executes the 'nvidia-smi' command to get GPU information
  gpu_info = !nvidia-smi

  # Converts the output of 'nvidia-smi' to a string
  gpu_info = '\n'.join(gpu_info)

  # Checks if the GPU information contains the word 'failed'
  if gpu_info.find('failed') >= 0:
    # If 'failed' is found, it indicates no GPU is connected
    print('Not connected to a GPU')
  else:
    # If 'failed' is not found, display the GPU information
    print(gpu_info)

from psutil import virtual_memory

def get_ram_info():
  """
  Gets information about the amount of RAM that is available to the Colab session.
  """

  ram_gb = virtual_memory().total / 1e9  # Get the total amount of RAM in gigabytes.
  print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))  # Print the amount of available RAM to the console.

  if ram_gb < 20:  # Check if the amount of available RAM is less than 20 gigabytes.
    print('Not using a high-RAM runtime')  # If the amount of available RAM is less than 20 gigabytes, print a message to the console.
  else:
    print('You are using a high-RAM runtime!')  # If the amount of available RAM is greater than or equal to 20 gigabytes, print a message to the console.

print(get_gpu_info())  # Prints the GPU information to the console.
print(get_ram_info())  # Prints the RAM information to the console.

from google.colab import drive

def connect_to_drive():
  """
  Mounts the user's Google Drive to the `/content/drive` directory in the Colab session.
  """

  drive.mount('/content/drive')  # Mounts the user's Google Drive to the `/content/drive` directory.

"""Uncomment and run one of the 2 cells below to get the ParsBERT project from github."""

# !git clone https://github.com/hooshvare/parsbert.git parsbert  # Clones the ParsBERT repository from GitHub into a directory called `parsbert`.
# %cd /content/parsbert/scripts/  # Changes the current directory to the `scripts` directory within the ParsBERT repository.
# !rm -rf __pycache__  # Removes the `__pycache__` directory from the current directory.
# !ls  # Lists the contents of the current directory.

!wget https://github.com/hooshvare/parsbert/archive/refs/heads/master.zip  # Downloads the ParsBERT repository from GitHub.
!unzip /content/master.zip -d /content/  # Unzips the downloaded file into the `/content` directory.

!python --version  # Prints the version of Python that is installed on the Colab session.

!pip install --upgrade pip  # Upgrades the pip package installer to the latest version.

!pip install -q transformers torch scikit-learn dataclasses numpy filelock hazm clean-text[gpl] numba numpy torchtext torch torchvision pip install transformers[torch]


# Installs the following packages:
# * transformers: A library for natural language processing (NLP).
# * torch: A deep learning framework based on PyTorch.
# * scikit-learn: A machine learning library.
# * dataclasses: A library for creating data classes.
# * numpy: A library for working with arrays.
# * filelock: A library for locking files.
# * hazm: A library for Persian NLP.
# * clean-text: A library for cleaning text.
# * numba: A library for just-in-time (JIT) compilation.
# * numpy: A library for working with arrays. (Installed again because it is a dependency of transformers[torch].)
# * torchtext: A library for working with text data.
# * torch torchvision: A library for working with image data.
# * transformers[torch]: The PyTorch-specific dependencies for the transformers library.

# The `-q` flag suppresses output from the pip installer.

import numpy as np

def dummy_npwarn_decorator_factory():
  """
  Creates a dummy decorator that does nothing.

  This is used to prevent NumPy from issuing a warning about a change in the way that NumPy arrays are serialized.
  """

  def npwarn_decorator(x):
    return x

  return npwarn_decorator

# Sets the `_no_nep50_warning` attribute of the `numpy` module to the `dummy_npwarn_decorator_factory` function.
np._no_nep50_warning = getattr(np, '_no_nep50_warning', dummy_npwarn_decorator_factory)

# Import required packages

import numpy as np  # A library for working with arrays.
import pandas as pd  # A library for working with dataframes.

from sklearn.model_selection import train_test_split  # A library for splitting datasets into train and test sets.
from sklearn.metrics import classification_report  # A library for generating classification reports.
from sklearn.metrics import f1_score  # A library for calculating F1 scores.
from sklearn.utils import shuffle  # A library for shuffling data.

import hazm  # A library for Persian NLP.
from cleantext import clean  # A library for cleaning text.

import plotly.express as px  # A library for creating data visualizations.
import plotly.graph_objects as go  # A library for creating graph objects.
import matplotlib.pyplot as plt  # A library for creating graphs.

from tqdm.notebook import tqdm  # A library for creating progress bars.

import os  # A library for working with the operating system.
import re  # A library for working with regular expressions.
import json  # A library for working with JSON data.
import copy  # A library for copying objects.
import collections  # A library for working with collections.

#@title Kaggle Credential { display-mode: "form" }

username = 'mraliamani' #@param {type: "string"}
api_key = 'f181b1169b8f3e2bedf68238b71e792b' #@param {type: "string"}


if username and api_key:
    token = {"username": username, "key": api_key}

    !mkdir ~/.kaggle
    !mkdir /content/.kaggle
    with open('/content/.kaggle/kaggle.json', 'w') as f:
        json.dump(token, f)

    !cp /content/.kaggle/kaggle.json ~/.kaggle/kaggle.json
    !chmod 600 /root/.kaggle/kaggle.json

    print('Your are ready to use kaggle API!')

# Commented out IPython magic to ensure Python compatibility.
# Removes the `dataset` directory if it exists.
!rm -rf /content/dataset

# Creates the `dataset` directory.
!mkdir -p /content/dataset

# Changes the current directory to the `/content` directory.
# %cd /content/

# Downloads the TaaghChe dataset from Kaggle.
!kaggle datasets download saeedtqp/taaghche

# Unzips the downloaded file into the `/content/dataset` directory.
!unzip /content/taaghche.zip -d /content/dataset/

"""## Dataset

For this tutorial, I'm going to use one of the sentiment analysis datasets accessible from Kaggle ([Taaghche](https://www.kaggle.com/saeedtqp/taaghche)). You can use whatever dataset you have (Please let me know your results on different datasets you used).

Let's look at the Taaghche dataset and obtain some intuitions about the data, distribution, and any further operation regarding this particular case.

### Load the data using Pandas
"""

# Reads the TaaghChe dataset into a Pandas DataFrame.
data = pd.read_csv('/content/dataset/taghche.csv', encoding='utf-8')

# Selects the `comment` and `rate` columns from the DataFrame.
data = data[['comment', 'rate']]

# Prints the first few rows of the DataFrame.
data.head()

"""### Fixing Conflicts

As you might be realized, the dataset has some structural problems, as shown below.

![alt text](https://res.cloudinary.com/m3hrdadfi/image/upload/v1596398432/kaggle/data-structure-flaws_xoqprk.png)

For simplicity, I fix this problem by removing rows with the `rate` value of `None`. Furthermore, the dataset contains duplicated rows and missing values in the comment section.
"""

# Prints the data information to the console.
print('data information')
print(data.info(), '\n')

# Prints the number of missing values in each column to the console.
print('missing values stats')
print(data.isnull().sum(), '\n')

# Prints the first 5 rows with missing values in the `rate` column to the console.
print('some missing values')
print(data[data['rate'].isnull()].iloc[:5], '\n')

# handle some conflicts with the dataset structure
# you can find a reliable solution, for the sake of the simplicity
# I just remove these bad combinations!
data.loc[data['rate'] >= 6, 'rate'] = None  # Replaces all values in the `rate` column that are greater than or equal to 6 with `None`.

data = data.dropna(subset=['rate'])  # Removes all rows with missing values in the `rate` column.
data = data.dropna(subset=['comment'])  # Removes all rows with missing values in the `comment` column.
data = data.drop_duplicates(subset=['comment'], keep='first')  # Removes all duplicate rows based on the `comment` column.
data = data.reset_index(drop=True)  # Resets the index of the DataFrame.

# previous information after solving the conflicts

# print data information
print('data information')
print(data.info(), '\n')

# print missing values information
print('missing values stats')
print(data.isnull().sum(), '\n')

# print some missing values
print('some missing values')
print(data[data['rate'].isnull()].iloc[:5], '\n')

"""### Normalization / Preprocessing

The comments have different lengths based on words! Detecting the most normal range could help us find the maximum length of the sequences for the preprocessing step. On the other hand, we suppose that the minimum word combination for having a meaningful phrase for our learning process is 3.
"""

# calculate the length of comments based on their words
data['comment_len_by_words'] = data['comment'].apply(lambda t: len(hazm.word_tokenize(t)))

# calculate min and max length of comments based on their words
min_max_len = data["comment_len_by_words"].min(), data["comment_len_by_words"].max()

# print the results
print(f'Min: {min_max_len[0]} \tMax: {min_max_len[1]}')

def data_gl_than(data, less_than=100.0, greater_than=0.0, col='comment_len_by_words'):
  """Calculates the percentage of data that falls within a specific range in a pandas dataframe"""

  data_length = data[col].values

  data_glt = sum([1 for length in data_length if greater_than < length <= less_than])

  data_glt_rate = (data_glt / len(data_length)) * 100

  print(f'Texts with word length of greater than {greater_than} and less than {less_than} includes {data_glt_rate:.2f}% of the whole!')

data_gl_than(data, 256, 3)

minlim, maxlim = 3, 256

# remove comments with the length of fewer than three words
data['comment_len_by_words'] = data['comment_len_by_words'].apply(lambda len_t: len_t if minlim < len_t <= maxlim else None)
data = data.dropna(subset=['comment_len_by_words'])
data = data.reset_index(drop=True)

def enable_plotly_in_cell():
  """Enables Plotly in Colab cells"""

  import IPython
  from plotly.offline import init_notebook_mode

  display(IPython.core.display.HTML('''<script src="/static/components/requirejs/require.js"></script>'''))
  init_notebook_mode(connected=False)

# Plot the distribution of word counts within comments
fig = go.Figure()

fig.add_trace(go.Histogram(
    x=data['comment_len_by_words']
))

fig.update_layout(
    title_text='Distribution of word counts within comments',
    xaxis_title_text='Word Count',
    yaxis_title_text='Frequency',
    bargap=0.2,
    bargroupgap=0.2)

fig.show()

# List the unique rates in the dataset
unique_rates = list(sorted(data['rate'].unique()))
print(f'We have #{len(unique_rates)} unique rates: {unique_rates}')

# Plot the distribution of rates within comments
enable_plotly_in_cell()

fig = go.Figure()

groupby_rate = data.groupby('rate')['rate'].count()

fig.add_trace(go.Bar(
    x=list(sorted(groupby_rate.index)),
    y=groupby_rate.tolist(),
    text=groupby_rate.tolist(),
    textposition='auto'
))

fig.update_layout(
    title_text='Distribution of rate within comments',
    xaxis_title_text='Rate',
    yaxis_title_text='Frequency',
    bargap=0.2,
    bargroupgap=0.2)

fig.show()

"""For simplicity, I transformed the rate in a range of 0.0 to 5.0 to a binary form of negative (0) or positive (1) with a threshold. If the rate is less than 3.0, it labeled as negative otherwise specified as positive."""

def rate_to_label(rate, threshold=3.0):
  """Converts a rate to a sentiment label"""

  if rate <= threshold:
    return 'negative'
  else:
    return 'positive'


data['label'] = data['rate'].apply(lambda t: rate_to_label(t, 3.0))
labels = list(sorted(data['label'].unique()))
data.head()

"""Cleaning is the final step in this section. Our cleaned method includes these steps:

- fixing unicodes
- removing specials like a phone number, email, url, new lines, ...
- cleaning HTMLs
- normalizing
- removing emojis
"""

def cleanhtml(raw_html):
  """Cleans HTML tags from a string"""

  cleanr = re.compile('<.*?>')
  cleantext = re.sub(cleanr, '', raw_html)
  return cleantext


def cleaning(text):
  """Cleans a string for sentiment analysis"""

  text = text.strip()

  # regular cleaning
  text = clean(text,
    fix_unicode=True,
    to_ascii=False,
    lower=True,
    no_line_breaks=True,
    no_urls=True,
    no_emails=True,
    no_phone_numbers=True,
    no_numbers=False,
    no_digits=False,
    no_currency_symbols=True,
    no_punct=False,
    replace_with_url="",
    replace_with_email="",
    replace_with_phone_number="",
    replace_with_number="",
    replace_with_digit="0",
    replace_with_currency_symbol="",
  )

  # cleaning htmls
  text = cleanhtml(text)

  # normalizing
  normalizer = hazm.Normalizer()
  text = normalizer.normalize(text)

  # removing wierd patterns
  # The unicodes that you are removing in your cleaning() function represent a variety of things, including:
  # Emoticons (e.g. \U0001F600-\U0001F64F)
  # Symbols & pictographs (e.g. \U0001F300-\U0001F5FF)
  # Transport & map symbols (e.g. \U0001F680-\U0001F6FF)
  # Flags (iOS) (e.g. \U0001F1E0-\U0001F1FF)
  # Miscellaneous symbols (e.g. \U00002702-\U000027B0, \U000024C2-\U0001F251)
  # Combining diacritic marks (e.g. \u200d)
  # Variation selectors (e.g. \ufe0f)
  wierd_pattern = re.compile("["
    u"\U0001F600-\U0001F64F"  # emoticons
    u"\U0001F300-\U0001F5FF"  # symbols & pictographs
    u"\U0001F680-\U0001F6FF"  # transport & map symbols
    u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
    u"\U00002702-\U000027B0"
    u"\U000024C2-\U0001F251"
    u"\U0001f926-\U0001f937"
    u'\U00010000-\U0010ffff'
    u"\u200d"
    u"\u2640-\u2642"
    u"\u2600-\u2B55"
    u"\u23cf"
    u"\u23e9"
    u"\u231a"
    u"\u3030"
    u"\ufe0f"
    u"\u2069"
    u"\u2066"
    # u"\u200c"
    u"\u2068"
    u"\u2067"
    "]+", flags=re.UNICODE)

  text = wierd_pattern.sub(r'', text)

  # removing extra spaces, hashtags
  text = re.sub("#", "", text)
  text = re.sub("\s+", " ", text)

  return text

# Split the data to 4 parts in order to run the cleaning function without google colab getting disconnected.
# We need the quarter_length to do so.
quarter_length = data.shape[0] // 4
print(quarter_length)

# Conenct to drive in case you are running the code in another session.
connect_to_drive()

# Run the cleaning function on the first part of data and save it to google drive.

# progress bar
tqdm.pandas()

data_part1 = data['comment'][:quarter_length].progress_apply(cleaning)
data_part1.to_csv('/content/drive/My Drive/data_part1.csv', index=False)

# Run the cleaning function on the second part of data and save it to google drive.

# progress bar
tqdm.pandas()

data_part2 = data['comment'][quarter_length: 2 * quarter_length].progress_apply(cleaning)
data_part2.to_csv('/content/drive/My Drive/data_part2.csv', index=False)

# Run the cleaning function on the third part of data and save it to google drive.

tqdm.pandas()

data_part3 = data['comment'][2 * quarter_length: 3 * quarter_length].progress_apply(cleaning)
data_part3.to_csv('/content/drive/My Drive/data_part3.csv', index=False)

# Run the cleaning function on the last part of data and save it to google drive.

tqdm.pandas()

data_part4 = data['comment'][3 * quarter_length:].progress_apply(cleaning)
data_part4.to_csv('/content/drive/My Drive/data_part4.csv', index=False)

# Conenct to drive in case you are running the code in another session.
connect_to_drive()

# This code reads the data from the CSV file located at '/content/drive/MyDrive/data_part1.csv' and stores it in the data_part1 variable.
data_part1 = pd.read_csv('/content/drive/MyDrive/data_part1.csv')

# This code drops the column named 'Unnamed: 0' from the data_part1 DataFrame.
data_part1.drop('Unnamed: 0', axis=1, inplace=True)

# This code prints the first few rows of the data_part1 DataFrame.
print(data_part1.head())

# This code reads the data from the CSV file located at '/content/drive/MyDrive/data_part2.csv' and stores it in the data_part2 variable.
data_part2 = pd.read_csv('/content/drive/MyDrive/data_part2.csv')

# This code drops the column named 'Unnamed: 0' from the data_part2 DataFrame.
data_part2.drop('Unnamed: 0', axis=1, inplace=True)

# This code prints the first few rows of the data_part2 DataFrame.
print(data_part2.head())

# This code reads the data from the CSV file located at '/content/drive/MyDrive/data_part3.csv' and stores it in the data_part3 variable.
data_part3 = pd.read_csv('/content/drive/MyDrive/data_part3.csv')

# This code drops the column named 'Unnamed: 0' from the data_part3 DataFrame.
data_part3.drop('Unnamed: 0', axis=1, inplace=True)

# This code prints the first few rows of the data_part3 DataFrame.
print(data_part3.head())

# This code reads the data from the CSV file located at '/content/drive/MyDrive/data_part4.csv' and stores it in the data_part4 variable.
data_part4 = pd.read_csv('/content/drive/MyDrive/data_part4.csv')

# This code drops the column named 'Unnamed: 0' from the data_part4 DataFrame.
data_part4.drop('Unnamed: 0', axis=1, inplace=True)

# This code prints the first few rows of the data_part4 DataFrame.
print(data_part4.head())

# This code locates the rows from the beginning of the DataFrame to the quarter_length and sets the 'cleaned_comment' column to the 'comment' column of the data_part1 DataFrame.
data.loc[:quarter_length, 'cleaned_comment'] = data_part1['comment']

# This code locates the rows from the quarter_length to 2 * quarter_length and sets the 'cleaned_comment' column to the 'comment' column of the data_part2 DataFrame.
data.loc[quarter_length: 2 * quarter_length, 'cleaned_comment'] = data_part2['comment']

# This code locates the rows from 2 * quarter_length to 3 * quarter_length and sets the 'cleaned_comment' column to the 'comment' column of the data_part3 DataFrame.
data.loc[2 * quarter_length: 3 * quarter_length, 'cleaned_comment'] = data_part3['comment']

# This code locates the rows from 3 * quarter_length to the end of the DataFrame and sets the 'cleaned_comment' column to the 'comment' column of the data_part4 DataFrame.
data.loc[3 * quarter_length:, 'cleaned_comment'] = data_part4['comment']

# This code prints the column names of the DataFrame.
print(data.columns)

# This code prints the first few rows of the DataFrame.
print(data.head())

tqdm.pandas()

# This code calculates the length of comments based on their words and stores the results in the 'cleaned_comment_len_by_words' column of the DataFrame.
data['cleaned_comment_len_by_words'] = data['cleaned_comment'].astype(str).progress_apply(lambda t: len(hazm.word_tokenize(t)))

# This code removes comments with the length of fewer than three words.
data['cleaned_comment_len_by_words'] = data['cleaned_comment_len_by_words'].progress_apply(lambda len_t: len_t if minlim < len_t <= maxlim else None)

# This code drops all rows that have a value of None in the 'cleaned_comment_len_by_words' column.
data = data.dropna(subset=['cleaned_comment_len_by_words'])

# This code resets the index of the DataFrame.
data = data.reset_index(drop=True)

# This code prints the first few rows of the DataFrame.
data.head()

# This code removes the 'cleaned_comment_len_by_words' column from the DataFrame.
data = data[['cleaned_comment', 'label']]

# This code renames the 'cleaned_comment' column to 'comment'.
data.columns = ['comment', 'label']

# This code prints the first few rows of the DataFrame.
data.head()

# This code prints the number of labels and the list of labels.
print(f'We have #{len(labels)} labels: {labels}')

# This code saves the DataFrame to the CSV file located at '/content/drive/My Drive/parsbert_df.csv'.
data.to_csv('/content/drive/My Drive/parsbert_df.csv', index=False)

# Connect to drive if it is not connected.
connect_to_drive()

data = pd.read_csv('/content/drive/My Drive/parsbert_df.csv')

# This code drops the column named 'Unnamed: 0' from the DataFrame.
data.drop('Unnamed: 0', axis=1, inplace=True)

# This code prints the first few rows of the DataFrame.
print(data.head())

"""### Handling Unbalanced Data"""

# This code calls the enable_plotly_in_cell function to enable Plotly visualizations in Jupyter notebooks.
enable_plotly_in_cell()

# This code imports the Figure and Bar classes from the plotly.graph_objs module.
from plotly.graph_objs import Figure, Bar

# This code creates a new Figure object.
fig = Figure()

# This code groups the data by the 'label' column and counts the number of occurrences of each label.
groupby_label = data.groupby('label')['label'].count()

# This code adds a bar trace to the figure. The x-axis values are the sorted list of labels, the y-axis values are the counts of each label, the text labels are the counts of each label, and the text positions are set to 'auto'.
fig.add_trace(Bar(
    x=list(sorted(groupby_label.index)),
    y=groupby_label.tolist(),
    text=groupby_label.tolist(),
    textposition='auto'
))

# This code updates the layout of the figure. The title text is set to 'Distribution of label within comments [DATA]', the x-axis title text is set to 'Label', the y-axis title text is set to 'Frequency', the bar gap is set to 0.2, and the bar group gap is set to 0.2.
fig.update_layout(
    title_text='Distribution of label within comments [DATA]',
    xaxis_title_text='Label',
    yaxis_title_text='Frequency',
    bargap=0.2,
    bargroupgap=0.2
)

# This code displays the figure.
fig.show()

"""Again, for making things simple. We cut the dataset randomly based on the fewer label, the negative class."""

# This code filters the data to only include comments with the 'negative' label.
negative_data = data[data['label'] == 'negative']

# This code filters the data to only include comments with the 'positive' label.
positive_data = data[data['label'] == 'positive']

# This code finds the minimum of the lengths of the negative and positive data.
cutting_point = min(len(negative_data), len(positive_data))

# If the cutting point is less than or equal to the length of the negative data, then a random sample of the negative data is taken with the size equal to the cutting point. The index of the DataFrame is then reset.
if cutting_point <= len(negative_data):
  negative_data = negative_data.sample(n=cutting_point).reset_index(drop=True)

# If the cutting point is less than or equal to the length of the positive data, then a random sample of the positive data is taken with the size equal to the cutting point. The index of the DataFrame is then reset.
if cutting_point <= len(positive_data):
  positive_data = positive_data.sample(n=cutting_point).reset_index(drop=True)

# This code concatenates the negative and positive data together.
new_data = pd.concat([negative_data, positive_data])

# This code randomly shuffles the rows of the DataFrame and resets the index.
new_data = new_data.sample(frac=1).reset_index(drop=True)

# This code prints information about the DataFrame.
new_data.info()

# This code calls the enable_plotly_in_cell function to enable Plotly visualizations in Jupyter notebooks.
enable_plotly_in_cell()

# This code imports the Figure and Bar classes from the plotly.graph_objs module.
from plotly.graph_objs import Figure, Bar

# This code creates a new Figure object.
fig = Figure()

# This code groups the new_data by the 'label' column and counts the number of occurrences of each label.
groupby_label = new_data.groupby('label')['label'].count()

# This code adds a bar trace to the figure. The x-axis values are the sorted list of labels, the y-axis values are the counts of each label, the text labels are the counts of each label, and the text positions are set to 'auto'.
fig.add_trace(Bar(
    x=list(sorted(groupby_label.index)),
    y=groupby_label.tolist(),
    text=groupby_label.tolist(),
    textposition='auto'
))

# This code updates the layout of the figure. The title text is set to 'Distribution of label within comments [NEW DATA]', the x-axis title text is set to 'Label', the y-axis title text is set to 'Frequency', the bar gap is set to 0.2, and the bar group gap is set to 0.2.
fig.update_layout(
    title_text='Distribution of label within comments [NEW DATA]',
    xaxis_title_text='Label',
    yaxis_title_text='Frequency',
    bargap=0.2,
    bargroupgap=0.2
)

# This code displays the figure.
fig.show()

new_data.head()

"""## Train,Validation,Test split

To achieve a globalized model, we need to split the cleaned dataset into train, valid, test sets due to size of the data. In this tutorial, I have considered a rate of **0.1** for both *valid*, *test* sets. For splitting, I use `train_test_split` provided by Sklearn package with stratifying on the label for preserving the distribution balance.
"""

# This code creates a new column called 'label_id' and assigns the index of the corresponding label in the 'labels' list to each row.
new_data['label_id'] = new_data['label'].apply(lambda t: labels.index(t))

# This code splits the new_data into training, validation, and test sets. The test set size is set to 10%, the random state is set to 1, and the stratification is based on the 'label' column.
train, test = train_test_split(new_data, test_size=0.1, random_state=1, stratify=new_data['label'])

# This code splits the training set into training and validation sets. The validation set size is set to 10%, the random state is set to 1, and the stratification is based on the 'label' column.
train, valid = train_test_split(train, test_size=0.1, random_state=1, stratify=train['label'])

# This code resets the indexes of the training, validation, and test sets.
train = train.reset_index(drop=True)
valid = valid.reset_index(drop=True)
test = test.reset_index(drop=True)

# This code creates lists of the comments and labels for the training, validation, and test sets.
x_train, y_train = train['comment'].values.tolist(), train['label_id'].values.tolist()
x_valid, y_valid = valid['comment'].values.tolist(), valid['label_id'].values.tolist()
x_test, y_test = test['comment'].values.tolist(), test['label_id'].values.tolist()

# This code prints the shapes of the training, validation, and test sets.
print(train.shape)
print(valid.shape)
print(test.shape)

"""Now, my favorite part comes. First of all, I follow the model using *PyTorch*, and next, do the same processes using *TensorFlow* and finally use the ParsBERT script to do all the things once in a desired form for HuggignFace.

![BERT INPUTS](https://res.cloudinary.com/m3hrdadfi/image/upload/v1595158991/kaggle/bert_inputs_w8rith.png)

As you may know, the BERT model input is a combination of 3 embeddings.
- Token embeddings: WordPiece token vocabulary (WordPiece is another word segmentation algorithm, similar to BPE)
- Segment embeddings: for pair sentences [A-B] marked as $E_A$ or $E_B$ mean that it belongs to the first sentence or the second one.
- Position embeddings: specify the position of words in a sentence

## PyTorch
"""

# This code imports the BertConfig, BertTokenizer, BertModel classes from the transformers library.
from transformers import BertConfig, BertTokenizer, BertModel

# This code imports the AdamW, get_linear_schedule_with_warmup functions from the transformers library.
from transformers import AdamW, get_linear_schedule_with_warmup

# This code imports the torch, torch.nn, and torch.nn.functional modules.
import torch
import torch.nn as nn
import torch.nn.functional as F

"""### Configuration"""

# This code checks if CUDA is available.
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# This code prints the device that will be used for training.
print(f'device: {device}')

# This code sets the train_on_gpu variable to True if CUDA is available, and False otherwise.
train_on_gpu = torch.cuda.is_available()

# This code prints a message depending on whether CUDA is available or not.
if not train_on_gpu:
	print('CUDA is not available.  Training on CPU ...')
else:
	print('CUDA is available!  Training on GPU ...')

# This code sets the following hyperparameters:
# * MAX_LEN: The maximum length of a tokenized input sequence.
# * TRAIN_BATCH_SIZE: The batch size for training.
# * VALID_BATCH_SIZE: The batch size for validation.
# * TEST_BATCH_SIZE: The batch size for testing.
# * EPOCHS: The number of epochs to train for.
# * EEVERY_EPOCH: The number of steps to take before evaluating the model on the validation set.
# * LEARNING_RATE: The learning rate.
# * CLIP: The gradient clipping value.

MAX_LEN = 128
TRAIN_BATCH_SIZE = 16
VALID_BATCH_SIZE = 16
TEST_BATCH_SIZE = 16

EPOCHS = 3
EEVERY_EPOCH = 1000
LEARNING_RATE = 2e-5
CLIP = 0.0

# This code sets the following paths:
# * MODEL_NAME_OR_PATH: The path to the pre-trained BERT model.
# * OUTPUT_PATH: The path to the output model.

MODEL_NAME_OR_PATH = 'HooshvareLab/bert-fa-base-uncased'
OUTPUT_PATH = '/content/bert-fa-base-uncased-sentiment-taaghceh/pytorch_model.bin'

# This code creates the directory for the output model if it does not already exist.
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

# This code creates a dictionary called label2id that maps each label to its corresponding index.
label2id = {label: i for i, label in enumerate(labels)}

# This code creates a dictionary called id2label that maps each index to its corresponding label.
id2label = {v: k for k, v in label2id.items()}

# This code prints the label2id and id2label dictionaries.
print(f'label2id: {label2id}')
print(f'id2label: {id2label}')

# This code creates a new BertTokenizer object using the pre-trained model located at MODEL_NAME_OR_PATH.
tokenizer = BertTokenizer.from_pretrained(MODEL_NAME_OR_PATH)

# This code creates a new BertConfig object using the pre-trained model located at MODEL_NAME_OR_PATH. The label2id and id2label dictionaries are also passed to the config object.
config = BertConfig.from_pretrained(
    MODEL_NAME_OR_PATH, **{
        'label2id': label2id,
        'id2label': id2label,
    })

# This code prints the JSON representation of the config object.
print(config.to_json_string())

"""### Input Embeddings"""

# This code generates a random integer between 0 and the length of the training set.
idx = np.random.randint(0, len(train))

# This code selects the comment and label at the randomly generated index from the training set.
sample_comment = train.iloc[idx]['comment']
sample_label = train.iloc[idx]['label']

# This code prints the sample comment and label.
print(f'Sample: \n{sample_comment}\n{sample_label}')

# Comment: This code tokenizes the sample comment and converts the tokens into token IDs.
# Token IDs are useful for representing tokens in a numerical form, which is necessary for machine learning tasks.tokens = tokenizer.tokenize(sample_comment)
token_ids = tokenizer.convert_tokens_to_ids(tokens)

print(f'  Comment: {sample_comment}')
print(f'   Tokens: {tokenizer.convert_tokens_to_string(tokens)}')
print(f'Token IDs: {token_ids}')

# This code calls the `encode_plus` method on the `tokenizer` object.

# The `encode_plus` method returns a dictionary that contains the following keys:
# * `input_ids`: A tensor of token IDs.
# * `token_type_ids`: A tensor of token type IDs.
# * `attention_mask`: A tensor of attention masks.
encoding = tokenizer.encode_plus(
    sample_comment,
    max_length=32,
    truncation=True,
    add_special_tokens=True, # Add '[CLS]' and '[SEP]'
    return_token_type_ids=True,
    return_attention_mask=True,
    padding='max_length',
    return_tensors='pt',  # Return PyTorch tensors
)

# The following code prints the keys of the `encoding` dictionary, followed by the values of each key.
print(f'Keys: {encoding.keys()}\n')
for k in encoding.keys():
    print(f'{k}:\n{encoding[k]}')

"""### Dataset"""

class TaaghcheDataset(torch.utils.data.Dataset):
  """ Create a PyTorch dataset for Taaghche. """

  def __init__(self, tokenizer, comments, targets=None, label_list=None, max_len=128):
    """
    Args:
      tokenizer: A tokenizer object.
      comments: A list of comments.
      targets: A list of targets.
      label_list: A list of labels.
      max_len: The maximum length of a tokenized input sequence.
    """

    self.comments = comments
    self.targets = targets
    self.has_target = isinstance(targets, list) or isinstance(targets, np.ndarray)

    self.tokenizer = tokenizer
    self.max_len = max_len

    self.label_map = {label: i for i, label in enumerate(label_list)} if isinstance(label_list, list) else {}

  def __len__(self):
    """
    Returns:
      The length of the dataset.
    """

    return len(self.comments)

  def __getitem__(self, item):
    """
    Args:
      item: The index of the item to be returned.

    Returns:
      A dictionary containing the following keys:
        * comment: The comment at the given index.
        * input_ids: The token IDs of the comment.
        * attention_mask: The attention mask for the comment.
        * token_type_ids: The token type IDs for the comment.
        * targets: The target for the comment (if available).
    """

    comment = str(self.comments[item])

    if self.has_target:
      target = self.label_map.get(str(self.targets[item]), str(self.targets[item]))

    encoding = self.tokenizer.encode_plus(
        comment,
        add_special_tokens=True,
        truncation=True,
        max_length=self.max_len,
        return_token_type_ids=True,
        padding='max_length',
        return_attention_mask=True,
        return_tensors='pt')

    inputs = {
        'comment': comment,
        'input_ids': encoding['input_ids'].flatten(),
        'attention_mask': encoding['attention_mask'].flatten(),
        'token_type_ids': encoding['token_type_ids'].flatten(),
    }

    if self.has_target:
      inputs['targets'] = torch.tensor(target, dtype=torch.long)

    return inputs

def create_data_loader(x, y, tokenizer, max_len, batch_size, label_list):
  """
  Args:
    x: A list of comments.
    y: A list of targets.
    tokenizer: A tokenizer object.
    max_len: The maximum length of a tokenized input sequence.
    batch_size: The batch size.
    label_list: A list of labels.

  Returns:
    A PyTorch data loader.
  """

  dataset = TaaghcheDataset(
      comments=x,
      targets=y,
      tokenizer=tokenizer,
      max_len=max_len,
      label_list=label_list)

  return torch.utils.data.DataLoader(dataset, batch_size=batch_size)

# This code creates a list of labels.
label_list = ['negative', 'positive']

# This code creates a PyTorch data loader for the training set. The following arguments are passed to the create_data_loader function:
# * x: The comments in the training set.
# * y: The labels in the training set.
# * tokenizer: The tokenizer object.
# * max_len: The maximum length of a tokenized input sequence.
# * batch_size: The batch size.
# * label_list: The list of labels.

train_data_loader = create_data_loader(train['comment'].to_numpy(), train['label'].to_numpy(), tokenizer, MAX_LEN, TRAIN_BATCH_SIZE, label_list)

# This code creates a PyTorch data loader for the validation set. The following arguments are passed to the create_data_loader function:
# * x: The comments in the validation set.
# * y: The labels in the validation set.
# * tokenizer: The tokenizer object.
# * max_len: The maximum length of a tokenized input sequence.
# * batch_size: The batch size.
# * label_list: The list of labels.

valid_data_loader = create_data_loader(valid['comment'].to_numpy(), valid['label'].to_numpy(), tokenizer, MAX_LEN, VALID_BATCH_SIZE, label_list)

# This code creates a PyTorch data loader for the test set. The following arguments are passed to the create_data_loader function:
# * x: The comments in the test set.
# * y: None (since the labels are not available for the test set).
# * tokenizer: The tokenizer object.
# * max_len: The maximum length of a tokenized input sequence.
# * batch_size: The batch size.
# * label_list: The list of labels.

test_data_loader = create_data_loader(test['comment'].to_numpy(), None, tokenizer, MAX_LEN, TEST_BATCH_SIZE, label_list)

# This code gets the next batch of data from the train_data_loader.
sample_data = next(iter(train_data_loader))

# This code prints the keys of the sample_data dictionary.
print(sample_data.keys())

# This code prints the comment in the sample_data dictionary.
print(sample_data['comment'])

# This code prints the shape of the input_ids tensor in the sample_data dictionary.
print(sample_data['input_ids'].shape)

# This code prints the first 10 elements of the input_ids tensor in the sample_data dictionary.
print(sample_data['input_ids'][0, :])

# This code prints the shape of the attention_mask tensor in the sample_data dictionary.
print(sample_data['attention_mask'].shape)

# This code prints the first 10 elements of the attention_mask tensor in the sample_data dictionary.
print(sample_data['attention_mask'][0, :])

# This code prints the shape of the token_type_ids tensor in the sample_data dictionary.
print(sample_data['token_type_ids'].shape)

# This code prints the first 10 elements of the token_type_ids tensor in the sample_data dictionary.
print(sample_data['token_type_ids'][0, :])

# This code prints the shape of the targets tensor in the sample_data dictionary.
print(sample_data['targets'].shape)

# This code prints the first element of the targets tensor in the sample_data dictionary.
print(sample_data['targets'][0])

# This code gets the next batch of data from the test_data_loader.
sample_test = next(iter(test_data_loader))

# This code prints the keys of the sample_test dictionary.
print(sample_test.keys())

"""### Model

During the implementation of the model, sometime, you may be faced with this kind of error. It said you used all the Cuda-Memory for solving. There are many ways for the simple one is to clear the Cuda cache memory!

![Cuda-Error](https://res.cloudinary.com/m3hrdadfi/image/upload/v1599979552/kaggle/cuda-error_iyqh4o.png)


**Simple Solution**
```python
import torch, gc

gc.collect()
torch.cuda.empty_cache()

!nvidia-smi
```
"""

class SentimentModel(nn.Module):

  def __init__(self, config):
    """
    Args:
      config: The configuration object for the model.
    """

    super(SentimentModel, self).__init__()

    self.bert = BertModel.from_pretrained(MODEL_NAME_OR_PATH)
    self.dropout = nn.Dropout(config.hidden_dropout_prob)
    self.classifier = nn.Linear(config.hidden_size, config.num_labels)

  def forward(self, input_ids, attention_mask, token_type_ids):
    """
    Args:
      input_ids: The input IDs for the model.
      attention_mask: The attention mask for the model.
      token_type_ids: The token type IDs for the model.

    Returns:
      The logits for the model.
    """

    _, pooled_output = self.bert(
        input_ids=input_ids,
        attention_mask=attention_mask,
        token_type_ids=token_type_ids,
        return_dict=False)

    pooled_output = self.dropout(pooled_output)
    logits = self.classifier(pooled_output)

    return logits

# This code imports the torch and gc libraries.
import torch, gc

# This code calls the gc.collect() method to collect garbage.
gc.collect()
# This code calls the torch.cuda.empty_cache() method to empty the CUDA cache.
torch.cuda.empty_cache()
# This code sets the pt_model variable to None.
pt_model = None

# This code calls the nvidia-smi command to show the status of the GPU.
!nvidia-smi

# This code creates a new SentimentModel object using the config object.
pt_model = SentimentModel(config=config)
pt_model = pt_model.to(device) # This code moves the model to the device.

print('pt_model', type(pt_model)) # This code prints the type of the pt_model object.

# This code assigns the comment, input IDs, attention mask, token type IDs, and targets from the sample_data dictionary to separate variables.
sample_data_comment = sample_data['comment']
sample_data_input_ids = sample_data['input_ids']
sample_data_attention_mask = sample_data['attention_mask']
sample_data_token_type_ids = sample_data['token_type_ids']
sample_data_targets = sample_data['targets']

# This code moves the input IDs, attention mask, token type IDs, and targets to the GPU.
sample_data_input_ids = sample_data_input_ids.to(device)
sample_data_attention_mask = sample_data_attention_mask.to(device)
sample_data_token_type_ids = sample_data_token_type_ids.to(device)
sample_data_targets = sample_data_targets.to(device)

# This code calls the forward method of the pt_model object to get the logits.
outputs = pt_model(sample_data_input_ids, sample_data_attention_mask, sample_data_token_type_ids)

# This code applies the softmax function to the logits along the first dimension.
# outputs = F.softmax(outputs, dim=1)

# This code gets the predictions by taking the maximum of the logits along the first dimension.
_, preds = torch.max(outputs, dim=1)

# This code prints the first 5 rows of the logits.
print(outputs[:5, :])

# This code prints the first 5 predictions.
print(preds[:5])

sample_data_input_ids

"""### Training"""

def simple_accuracy(y_true, y_pred):
  """
  Args:
    y_true: The ground truth labels.
    y_pred: The predicted labels.

  Returns:
    The accuracy.
  """

  return (y_true == y_pred).mean()

def acc_and_f1(y_true, y_pred, average='weighted'):
  """
  Args:
    y_true: The ground truth labels.
    y_pred: The predicted labels.
    average: The averaging method for the f1 score.

  Returns:
    A dictionary containing the accuracy and f1 score.
  """

  acc = simple_accuracy(y_true, y_pred)
  f1 = f1_score(y_true=y_true, y_pred=y_pred, average=average)
  return {
      "acc": acc,
      "f1": f1,
  }

def y_loss(y_true, y_pred, losses):
  """
  Args:
    y_true: The ground truth labels.
    y_pred: The predicted labels.
    losses: The losses.

  Returns:
    The ground truth labels, predicted labels, and mean loss.
  """

  y_true = torch.stack(y_true).cpu().detach().numpy()
  y_pred = torch.stack(y_pred).cpu().detach().numpy()
  y = [y_true, y_pred]
  loss = np.mean(losses)

  return y, loss


def eval_op(model, data_loader, loss_fn):
  """
  Args:
    model: The model to be evaluated.
    data_loader: The data loader to use for evaluation.
    loss_fn: The loss function to use for evaluation.

  Returns:
    The ground truth labels, predicted labels, and mean loss.
  """

  model.eval()

  losses = []
  y_pred = []
  y_true = []

  with torch.no_grad():
    for dl in tqdm(data_loader, total=len(data_loader), desc="Evaluation... "):

      input_ids = dl['input_ids']
      attention_mask = dl['attention_mask']
      token_type_ids = dl['token_type_ids']
      targets = dl['targets']

      # move tensors to GPU if CUDA is available
      input_ids = input_ids.to(device)
      attention_mask = attention_mask.to(device)
      token_type_ids = token_type_ids.to(device)
      targets = targets.to(device)

      # compute predicted outputs by passing inputs to the model
      outputs = model(
          input_ids=input_ids,
          attention_mask=attention_mask,
          token_type_ids=token_type_ids)

      # convert output probabilities to predicted class
      _, preds = torch.max(outputs, dim=1)

      # calculate the batch loss
      loss = loss_fn(outputs, targets)

      # accumulate all the losses
      losses.append(loss.item())

      y_pred.extend(preds)
      y_true.extend(targets)

  eval_y, eval_loss = y_loss(y_true, y_pred, losses)
  return eval_y, eval_loss


def train_op(model,
              data_loader,
              loss_fn,
              optimizer,
              scheduler,
              step=0,
              print_every_step=100,
              eval=False,
              eval_cb=None,
              eval_loss_min=np.Inf,
              eval_data_loader=None,
              clip=0.0):

  """
  Args:
    model: The model to be trained.
    data_loader: The data loader to use for training.
    loss_fn: The loss function to use for training.
    optimizer: The optimizer to use for training.
    scheduler: The scheduler to use for training.
    step: The current step.
    print_every_step: The number of steps between printing training information.
    eval: Whether to evaluate the model after each training step.
    eval_cb: A callback function to be called after each evaluation.
    eval_loss_min: The minimum evaluation loss so far.
    eval_data_loader: The data loader to use for evaluation.
    clip: The gradient clipping value.

  Returns:
    The ground truth labels, predicted labels, current step, and minimum evaluation loss.
  """

  model.train()

  losses = []
  y_pred = []
  y_true = []

  for dl in tqdm(data_loader, total=len(data_loader), desc="Training... "):
    step += 1

    input_ids = dl['input_ids']
    attention_mask = dl['attention_mask']
    token_type_ids = dl['token_type_ids']
    targets = dl['targets']

    # move tensors to GPU if CUDA is available
    input_ids = input_ids.to(device)
    attention_mask = attention_mask.to(device)
    token_type_ids = token_type_ids.to(device)
    targets = targets.to(device)

    # clear the gradients of all optimized variables
    optimizer.zero_grad()

    # compute predicted outputs by passing inputs to the model
    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask,
        token_type_ids=token_type_ids)

    # convert output probabilities to predicted class
    _, preds = torch.max(outputs, dim=1)

    # calculate the batch loss
    loss = loss_fn(outputs, targets)

    # accumulate all the losses
    losses.append(loss.item())

    # compute gradient of the loss with respect to model parameters
    loss.backward()

    # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
    if clip > 0.0:
      nn.utils.clip_grad_norm_(model.parameters(), max_norm=clip)

    # perform optimization step
    optimizer.step()

    # perform scheduler step
    scheduler.step()

    y_pred.extend(preds)
    y_true.extend(targets)

    if eval:
      train_y, train_loss = y_loss(y_true, y_pred, losses)
      train_score = acc_and_f1(train_y[0], train_y[1], average='weighted')

      if step % print_every_step == 0:
        eval_y, eval_loss = eval_op(model, eval_data_loader, loss_fn)
        eval_score = acc_and_f1(eval_y[0], eval_y[1], average='weighted')

        if hasattr(eval_cb, '__call__'):
          eval_loss_min = eval_cb(model, step, train_score, train_loss, eval_score, eval_loss, eval_loss_min)

  train_y, train_loss = y_loss(y_true, y_pred, losses)

  return train_y, train_loss, step, eval_loss_min

# AdamW optimizer is used with the learning rate set to LEARNING_RATE.
# The correct_bias argument is set to False to disable bias correction. This is because bias correction can lead to unstable training in some cases.
optimizer = AdamW(pt_model.parameters(), lr=LEARNING_RATE, correct_bias=False)
# A linear learning rate scheduler is created with the following parameters:
# optimizer: The optimizer to use with the scheduler.
# num_warmup_steps: The number of warmup steps. During the warmup steps, the learning rate is linearly increased from 0 to the initial learning rate.
# num_training_steps: The total number of training steps.
total_steps = len(train_data_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps=total_steps
)

# The cross-entropy loss function is used.
loss_fn = nn.CrossEntropyLoss()

# The initial step number is set to 0.
step = 0
# The minimum evaluation loss is set to positive infinity.
eval_loss_min = np.Inf
# A dictionary is created to store the training and evaluation history.
history = collections.defaultdict(list)


# An evaluation callback function is created. This function is called after each evaluation step.
# The callback function prints the training and evaluation loss and accuracy.
# If the evaluation loss is lower than the minimum evaluation loss, the model is saved.
def eval_callback(epoch, epochs, output_path):
    def eval_cb(model, step, train_score, train_loss, eval_score, eval_loss, eval_loss_min):
        statement = ''
        statement += 'Epoch: {}/{}...'.format(epoch, epochs)
        statement += 'Step: {}...'.format(step)

        statement += 'Train Loss: {:.6f}...'.format(train_loss)
        statement += 'Train Acc: {:.3f}...'.format(train_score['acc'])

        statement += 'Valid Loss: {:.6f}...'.format(eval_loss)
        statement += 'Valid Acc: {:.3f}...'.format(eval_score['acc'])

        print(statement)

        if eval_loss <= eval_loss_min:
            print('Validation loss decreased ({:.6f} --> {:.6f}).  Saving model ...'.format(
                eval_loss_min,
                eval_loss))

            torch.save(model.state_dict(), output_path)
            eval_loss_min = eval_loss

        return eval_loss_min


    return eval_cb


for epoch in tqdm(range(1, EPOCHS + 1), desc="Epochs... "):

  # Train the model for one epoch.
  train_y, train_loss, step, eval_loss_min = train_op(
      model=pt_model,
      data_loader=train_data_loader,
      loss_fn=loss_fn,
      optimizer=optimizer,
      scheduler=scheduler,
      step=step,
      print_every_step=EEVERY_EPOCH,
      eval=True,
      eval_cb=eval_callback(epoch, EPOCHS, OUTPUT_PATH),
      eval_loss_min=eval_loss_min,
      eval_data_loader=valid_data_loader,
      clip=CLIP)

  # Evaluate the model on the training set.
  train_score = acc_and_f1(train_y[0], train_y[1], average='weighted')

  # Evaluate the model on the validation set.
  eval_y, eval_loss = eval_op(
      model=pt_model,
      data_loader=valid_data_loader,
      loss_fn=loss_fn)

  eval_score = acc_and_f1(eval_y[0], eval_y[1], average='weighted')

  # Store the training and evaluation metrics.
  history['train_acc'].append(train_score['acc'])
  history['train_loss'].append(train_loss)
  history['val_acc'].append(eval_score['acc'])
  history['val_loss'].append(eval_loss)

"""### Prediction"""

def predict(model, comments, tokenizer, max_len=128, batch_size=32):
  """
  Predicts the labels for a given set of comments.

  Args:
    model: The PyTorch model to use for prediction.
    comments: A list of comments to predict labels for.
    tokenizer: A tokenizer to use for tokenizing the comments.
    max_len: The maximum length of the tokenized comments.
    batch_size: The batch size to use for prediction.

  Returns:
    predictions: A numpy array of the predicted labels.
    prediction_probs: A numpy array of the predicted class probabilities.
  """

  data_loader = create_data_loader(comments, None, tokenizer, max_len, batch_size, None)

  predictions = []
  prediction_probs = []


  model.eval()
  with torch.no_grad():
    for dl in tqdm(data_loader, position=0):
      input_ids = dl['input_ids']
      attention_mask = dl['attention_mask']
      token_type_ids = dl['token_type_ids']

      # move tensors to GPU if CUDA is available
      input_ids = input_ids.to(device)
      attention_mask = attention_mask.to(device)
      token_type_ids = token_type_ids.to(device)

      # compute predicted outputs by passing inputs to the model
      outputs = model(
          input_ids=input_ids,
          attention_mask=attention_mask,
          token_type_ids=token_type_ids)

      # convert output probabilities to predicted class
      _, preds = torch.max(outputs, dim=1)

      predictions.extend(preds)
      prediction_probs.extend(F.softmax(outputs, dim=1))

  predictions = torch.stack(predictions).cpu().detach().numpy()
  prediction_probs = torch.stack(prediction_probs).cpu().detach().numpy()

  return predictions, prediction_probs

# Convert test comments to NumPy array
test_comments = test['comment'].to_numpy()

# Make predictions on test comments
preds, probs = predict(pt_model, test_comments, tokenizer, max_len=128)

# Print shapes of predictions and probabilities
print(preds.shape, probs.shape)

# Convert test labels and predictions to integers
y_test = [label_list.index(label) for label in test['label'].values]
y_pred = preds

# Calculate F1 score
f1_score = f1_score(y_test, y_pred, average="weighted")

# Print F1 score
print(f'F1: {f1_score}')

# Print classification report
print(classification_report(y_test, y_pred, target_names=label_list))

"""## TensorFlow"""

# Import libraries from the Transformers library
from transformers import BertConfig, BertTokenizer
from transformers import TFBertModel, TFBertForSequenceClassification
from transformers import glue_convert_examples_to_features

# Import TensorFlow
import tensorflow as tf

"""### Configuration"""

# General configuration

# Maximum sequence length
MAX_LEN = 128

# Batch sizes for training, validation, and testing
TRAIN_BATCH_SIZE = 16
VALID_BATCH_SIZE = 16
TEST_BATCH_SIZE = 16

# Number of epochs to train for
EPOCHS = 3

# Number of steps to perform evaluation after each epoch
EEVERY_EPOCH = 1000

# Learning rate
LEARNING_RATE = 2e-5

# Gradient clipping threshold
CLIP = 0.0

# Path to pre-trained BERT model
MODEL_NAME_OR_PATH = 'HooshvareLab/bert-fa-base-uncased'

# Output path for trained model
OUTPUT_PATH = '/content/bert-fa-base-uncased-sentiment-taaghceh/tf_model.h5'

# Create directory for output path if it does not exist
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

# Create a dictionary mapping labels to IDs.
label2id = {label: i for i, label in enumerate(labels)}

# Create a dictionary mapping IDs to labels.
id2label = {v: k for k, v in label2id.items()}

# Print the label-to-ID and ID-to-label dictionaries.
print(f'label2id: {label2id}')
print(f'id2label: {id2label}')

# Create a BERT tokenizer from the pre-trained model.
tokenizer = BertTokenizer.from_pretrained(MODEL_NAME_OR_PATH)

# Create a BERT configuration from the pre-trained model.
config = BertConfig.from_pretrained(
    MODEL_NAME_OR_PATH,
    **{
        'label2id': label2id,
        'id2label': id2label,
    }
)

# Print the configuration in JSON format.
print(config.to_json_string())

"""### Input Embeddings / Dataset"""

# This class is used to represent a single example for simple sequence classification. It has the following attributes:

# guid: A unique identifier for the example.
# text_a: The first input text.
# text_b: The second input text (optional).
# label: The label for the example.
class InputExample:
  """ A single example for simple sequence classification. """

  def __init__(self, guid, text_a, text_b=None, label=None):
    """ Constructs a InputExample. """

    self.guid = guid
    self.text_a = text_a
    self.text_b = text_b
    self.label = label


# This function creates examples for the training and validation datasets. It takes the following arguments:

# tokenizer: A BERT tokenizer.
# x: A list of input texts.
# y: A list of labels (optional).
# maxlen: The maximum sequence length.
# output_mode: The output mode (either "classification" or "regression").
# is_tf_dataset: Whether to return a TensorFlow dataset or a list of NumPy arrays.
def make_examples(tokenizer, x, y=None, maxlen=128, output_mode="classification", is_tf_dataset=True):
  """Creates examples for the training and validation datasets."""

  # convert the list of InputExample objects to a list of Features objects.
  examples = []
  y = y if isinstance(y, list) or isinstance(y, np.ndarray) else [None] * len(x)

  for i, (_x, _y) in tqdm(enumerate(zip(x, y)), position=0, total=len(x)):
    guid = "%s" % i
    label = int(_y)

    if isinstance(_x, str):
      text_a = _x
      text_b = None
    else:
      assert len(_x) == 2
      text_a = _x[0]
      text_b = _x[1]

    examples.append(InputExample(guid=guid, text_a=text_a, text_b=text_b, label=label))

  # The function then converts the list of Features objects to a TensorFlow dataset or a list of NumPy arrays.
  features = glue_convert_examples_to_features(
      examples,
      tokenizer,
      maxlen,
      output_mode=output_mode,
      label_list=list(np.unique(y)))

  all_input_ids = []
  all_attention_masks = []
  all_token_type_ids = []
  all_labels = []

  for f in tqdm(features, position=0, total=len(examples)):
    if is_tf_dataset:
      all_input_ids.append(tf.constant(f.input_ids))
      all_attention_masks.append(tf.constant(f.attention_mask))
      all_token_type_ids.append(tf.constant(f.token_type_ids))
      all_labels.append(tf.constant(f.label))
    else:
      all_input_ids.append(f.input_ids)
      all_attention_masks.append(f.attention_mask)
      all_token_type_ids.append(f.token_type_ids)
      all_labels.append(f.label)

  if is_tf_dataset:
    dataset = tf.data.Dataset.from_tensor_slices(({
        'input_ids': all_input_ids,
        'attention_mask': all_attention_masks,
        'token_type_ids': all_token_type_ids
    }, all_labels))

    return dataset, features

  xdata = [np.array(all_input_ids), np.array(all_attention_masks), np.array(all_token_type_ids)]
  ydata = all_labels

  return [xdata, ydata], features

# The training and validation datasets are large, so it is more efficient to use TensorFlow datasets to store them.
# TensorFlow datasets can be batched and prefetched, which can improve the training and evaluation speed.
train_dataset_base, train_examples = make_examples(tokenizer, x_train, y_train, maxlen=128)
valid_dataset_base, valid_examples = make_examples(tokenizer, x_valid, y_valid, maxlen=128)

test_dataset_base, test_examples = make_examples(tokenizer, x_test, y_test, maxlen=128)
# The test dataset is smaller, so it is not as important to use a TensorFlow dataset to store it.
# In fact, it is often easier to work with a list of NumPy arrays when evaluating a model's performance.
[xtest, ytest], test_examples = make_examples(tokenizer, x_test, y_test, maxlen=128, is_tf_dataset=False)

for value in train_dataset_base.take(1):
    print(f'     input_ids: {value[0]["input_ids"]}')
    print(f'attention_mask: {value[0]["attention_mask"]}')
    print(f'token_type_ids: {value[0]["token_type_ids"]}')
    print(f'        target: {value[1]}')

def get_training_dataset(dataset, batch_size):
  """Creates a training dataset from the given dataset and batch size.

  Args:
    dataset: A TensorFlow dataset.
    batch_size: The batch size.

  Returns:
    A TensorFlow dataset that is repeated, shuffled, and batched.
  """

  dataset = dataset.repeat()
  dataset = dataset.shuffle(2048)
  dataset = dataset.batch(batch_size)

  return dataset


def get_validation_dataset(dataset, batch_size):
  """Creates a validation dataset from the given dataset and batch size.

  Args:
    dataset: A TensorFlow dataset.
    batch_size: The batch size.

  Returns:
    A TensorFlow dataset that is batched.
  """

  dataset = dataset.batch(batch_size)

  return dataset

# Get the training dataset, and split it into batches.
train_dataset = get_training_dataset(train_dataset_base, TRAIN_BATCH_SIZE)

# Get the validation dataset, and split it into batches.
valid_dataset = get_validation_dataset(valid_dataset_base, VALID_BATCH_SIZE)

# Calculate the number of training steps.
train_steps = len(train_examples) // TRAIN_BATCH_SIZE

# Calculate the number of validation steps.
valid_steps = len(valid_examples) // VALID_BATCH_SIZE

# Print the number of training and validation steps.
print(f"Train steps: {train_steps}")
print(f"Valid steps: {valid_steps}")

"""### Model"""

def build_model(model_name, config, learning_rate=3e-5):
  """Builds a TFBertForSequenceClassification model.

  Args:
    model_name: The name of the pre-trained BERT model to use.
    config: The model configuration.
    learning_rate: The learning rate for the optimizer.

  Returns:
    A TFBertForSequenceClassification model.
  """

  model = TFBertForSequenceClassification.from_pretrained(model_name, config=config)

  optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
  loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
  metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
  model.compile(optimizer=optimizer, loss=loss, metrics=[metric])

  return model

# Build the model.
model = build_model(MODEL_NAME_OR_PATH, config, learning_rate=LEARNING_RATE)

"""### Training"""

# Commented out IPython magic to ensure Python compatibility.
# # Train the model.
# %%time
# r = model.fit(
#     train_dataset,
#     validation_data=valid_dataset,
#     steps_per_epoch=train_steps,
#     validation_steps=valid_steps,
#     epochs=EPOCHS,
#     verbose=1)
# 
# # Calculate the final accuracy.
# final_accuracy = r.history['val_accuracy']
# 
# # Print the final accuracy.
# print('FINAL ACCURACY MEAN: ', np.mean(final_accuracy))

# Get the training and evaluation losses from the model history.
train_loss = r.history['loss']
val_loss = r.history['val_loss']

# Plot the training and evaluation losses.
plt.plot(train_loss, label='Training loss')
plt.plot(val_loss, label='Validation loss')

# Set the title and labels for the plot.
plt.title('Training and Evaluation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')

# Legend the plot.
plt.legend()

# Show the plot.
plt.show()

# Save the model in three different formats:
#   * HDF5 format
#   * TensorFlow SavedModel format
#   * Keras model format

# Save the model in HDF5 format.
model.save_pretrained('/content/drive/MyDrive/ParsBERT_h5model', save_format='h5')

# Save the model in TensorFlow SavedModel format.
tf.keras.Model.save(model, '/content/drive/MyDrive/ParsBERT_tfmodel', save_format='tf')

# Save the model in Keras model format.
tf.keras.Model.save(model, '/content/drive/MyDrive/ParsBERT_kerasmodel.keras', save_format='keras')

# Save the model to the directory specified by OUTPUT_PATH.
model.save_pretrained(os.path.dirname(OUTPUT_PATH))

"""### Evaluation / Prediction"""

# Evaluate the model on the test dataset.
ev = model.evaluate(test_dataset_base.batch(TEST_BATCH_SIZE))

# Print the evaluation results.
print()
print(f'Evaluation: {ev}')
print()

# Make predictions on the test dataset.
predictions = model.predict(xtest)

# Convert the predictions to class labels.
ypred = predictions[0].argmax(axis=-1).tolist()

# Print the classification report.
print()
print(classification_report(ytest, ypred, target_names=labels))
print()

# Calculate the F1 score.
print(f'F1: {f1_score(ytest, ypred, average="weighted")}')

"""## Script"""

# Remove the existing taaghche directory, if it exists.
!rm -rf /content/taaghche

# Create the taaghche directory, if it does not exist.
!mkdir -p /content/taaghche

# Select the relevant columns from the train, valid, and test datasets.
ntrain = train[['comment', 'label']]
ntrain.columns = ['text', 'label']

ndev = valid[['comment', 'label']]
ndev.columns = ['text', 'label']

ntest = test[['comment', 'label']]
ntest.columns = ['text', 'label']

# Save the train, dev, and test datasets to taaghche directory in TSV format.
ntrain.to_csv('/content/taaghche/' + 'train.tsv', sep='\t', index=False)
ndev.to_csv('/content/taaghche/' + 'dev.tsv', sep='\t', index=False)
ntest.to_csv('/content/taaghche/' + 'test.tsv', sep='\t', index=False)

# Commented out IPython magic to ensure Python compatibility.
# clone the ParsBERT repository
!git clone https://github.com/hooshvare/parsbert.git parsbert
# %cd /content/parsbert/scripts/
!rm -rf __pycache__
!ls

# Run the run_clf_finetuning.py script.
!python run_clf_finetuning.py

# Remove the existing bert-fa-base-uncased-sentiment-taaghceh-v2 directory, if it exists.
!rm -rf /content/bert-fa-base-uncased-sentiment-taaghceh-v2/

# Create the bert-fa-base-uncased-sentiment-taaghceh-v2 directory, if it does not exist.
!mkdir -p /content/bert-fa-base-uncased-sentiment-taaghceh-v2/

# Remove the existing scripts/runs directory and taaghche/cached_* files.
!rm -rf /content/scripts/runs
!rm /content/taaghche/cached_*


# Fine-tune the ParsBERT model on the taaghche dataset.
!python run_clf_finetuning.py \
    --labels positive,negative \
    --output_mode classification \
    --task_name taaghche \
    --model_name_or_path HooshvareLab/bert-fa-base-uncased \
    --data_dir /content/taaghche/ \
    --output_dir /content/bert-fa-base-uncased-sentiment-taaghceh-v2/ \
    --max_seq_length 128 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --learning_rate 2e-5 \
    --num_train_epochs 3.0 \
    --logging_steps 500 \
    --save_steps 1000 \
    --do_train \
    --do_eval \
    --do_predict \
    --overwrite_output_dir \
    --logging_first_step

